

var protseq = 
['>sp|P29600|SUBS_BACLE Subtilisin Savinase OS=Bacillus lentus PE=1 SV=1',
'AQSVPWGISRVQAPAAHNRGLTGSGVKVAVLDTGISTHPDLNIRGGASFVPGEPSTQDGN',
'GHGTHVAGTIAALNNSIGVLGVAPSAELYAVKVLGASGSGSVSSIAQGLEWAGNNGMHVA',
'NLSLGSPSPSATLEQAVNSATSRGVLVVAASGNSGAGSISYPARYANAMAVGATDQNNNR',
'ASFSQYGAGLDIVAPGVNVQSTYPGSTYASLNGTSMATPHVAGAAALVKQKNPSWSNVQI',
'RNHLKNTATSLGSTNLYGSGLVNAEAATR'].join('\n')


var getProteinStats = require('./lib/pepstats')

getProteinStats(protseq, {

    termini: true,
    monoisotopicWeights: false
   
}, (err, stats) => {

    console.log(stats)

})


